version: '3'
services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    depends_on:
      - retro-board
      - authentication
    volumes: 
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  retro-board:
    container_name: retro-board-service
    restart: always
    build: ./retro-board
    ports:
      - '3000:3000'
    environment:
      # - DEBUG=*
      - REDIS_URL=redis://retro-board-redis
      - DEVELOPMENT=true
    depends_on: 
      - mongo
    links:
      - mongo
      - redis

  authentication:
    container_name: authentication-service
    restart: always
    build: ./authentication
    ports:
      - '3001:3001'
    environment:
      - REDIS_URL=redis://retro-board-redis
    depends_on: 
      - mongo
    links:
      - mongo
      - redis

  mongo:
    container_name: retro-board-mongodb
    image: mongo
    # environment: 
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - /data/db
    #   - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    #   - ./mongo/data:/data/db
    ports: 
      - '27017:27017'
    command: --logpath=/dev/null
  redis:
    container_name: retro-board-redis
    image: redis
    ports:
      - '6379:6379'